---
title: \pkg{noaastormevents}-- A package to explore NCDC's database on US storm events and their impacts
author:
  - name: Ziyu Chen
    affiliation: Colorado State University
    address:
    - W Elizabeth Street
    - Fort Collins
    email:  zailchen17@icloud.com
  - name: Brooke Anderson
    affiliation: Colorado State University
    address:
    - Lake Street
    - Fort Collins
    email:  brooke.anderson@colostate.edu
abstract: >
  An abstract of less than 150 words.
preamble: >
  % Any extra latex you need in the preamble
output: rticles::rjournal_article
---

## Introduction

### Importance of studying impacts of storm events

Risks of mortality from a number of types of storm events have decreased over the past century, including for deaths from lightning \citep{Curran2000}, tornadoes \citep{Ashley2007}, ... . This decrease in part is related to an improved understanding of these risks and the development of better warnings and awareness \citep{Curran2000, Ashley2007}. This decline in mortality risk may have leveled off recently for some event types (e.g., lightning \citet{Ashley2007}).

While risks of death have decreased, property damage from storm events has increased over the past century [\citet{Curran2000} for lightning damage].

### Description of the database

This database is put together using a number of different sources, including newspaper reports \citep{Curran2000, Ashley2008flood}, calls to emergency agencies \citep{Curran2000}, law enforcement agencies \citep{Ashley2008flood}, government agencies \citep{Ashley2008flood}, ... . A main source for the events data in this database is from verifying NWS warnings to determine which warnings were accurate [see Hales and Kelly reference in \citet{Witt1998}].

This database evolved from efforts in the 1950s to record details of tornadoes, then expanded to include other event types, including severe hail, floods, and extreme wind \citep{Ashley2007}. The database officially began as the "Storm Data" database in 1959 \citep{Ashley2008flood}

Event times are in local standard time \citep{Ashley2008flood.

[Degree of missing data]

The database also includes descriptive paragraphs for events ... Information from this descriptive paragraph is sometimes used to varifity other information listed for a storm event (e.g., shelter type for tornado casualties \citet{Ashley2007}). These descriptive paragraphs tend to include more helpful details for more recent database entries than older ones \citep{Ashley2007}.

### Examples of use of the database in research

...

In lightning impacts research, this database has been used to identify high-risk states for lightning casualties and damages \citep{Curran2000}.

In another study, researchers used events data from this database to use for ground-truth validation of an algorithm for detecting hail \citep{Witt1998}.

Other studies have combined this database with other data sources for studies. Examples include a study of tornado impacts, which combined the Storm Events database with data collected during a long-term study \citep{Ashley2007}. Other example studies used a database generated in part from the Storm Events database [Rappaport dataset, including in \citet{Ashley2008flood}].

## Overview of the package

## Simple example of package use

## Example applications

[National map of county-level lightning deaths and injuries]

[Distribution of lightning deaths and injuries by month]

[Pairing with ACS to show county-level rates within decades]

Florida was found to have more than double the lightning-related casualties of any other US state in an earlier analysis of the Storm Events database \citep{Curran2000}. Florida is at much higher risks than most states of hurricanes, and hurricanes could cause lightning casualties. With this package, a user can explore county-level patterns in lightning casualties over several years. Since we have provided a way to link events with tropical storms, a user can separate lightning casualties between those that occurred in a county near in time and space to a passing tropical storm from other lightning events. [Note: Duclos reference in \citet{Curran2000} has older maps of county-level lightning casualties in Florida.]

[Lightning events in Florida over the period of our hurricane tracks data] 


## In-depth description of package

## Details of Storm Data database

### How the Storm Data database is collected and maintained

Data on severe storm events is collected every month by local National Weather Service offices \citep{Curran2000} and then collected, aggregated, shared, and maintained by a national office of NOAA (NCEI [?]). 

### Things to consider in using the database for research

While this database offers a wealth of data on severe storm impacts across the United States over multiple years, it has some limitations that should be considered when planning or interpreting research based on it.

The full storm database covers a large number of years ([x] to present). However, several elements of the dataset may vary over this period, so care should be taken in using the database for long-term studies. First the coverage of storm events has changed over time, with only ... covered from 1985 until ..., and an expansion to include ... after ... . Further, amounts of missing data for specific storm characteristics has decreased substantially with time from early years covered by the Storm Data database \citep{Curran2000}.

Storm events data tend to be underreported \citep{Ashley2008flood}, and the degree of underreporting can vary by event type, with less for large-scale storms like hurricanes and large-impact floods \citep{Ashley2008flood} and more for very localized events like lightning \citep{Curran2000}. For example, several studies have found evidence that lightning causualties are underreported in the Storm Data database [see Lopez, Mogil, and Cherington references in \citet{Curran2000}]. Another study found that lightning damages are also underreported [Holle reference in \citet{Curran2000}]. Small-scale events like hail \citep{Witt1998} are especially likely to be underreported.

The underreporting in the Storm Events database can lead to conservative estimates of impactes \citep{Ashley2008flood}.

Underreporting can be correlated with population density, with more underreporting in less populated areas, where fewer people are around to see and report an event \citep{Witt1998, Ashley2007}.

One study calls the percent of severe events reported in the Storm Events database the "ground-truth verification efficiency" or "verification efficiency" \citep{Witt1998}.

Data can be underreported both in terms of number of events reported (i.e., completely missing some reports) and in underreporting impacts of events that are included. For example, one study found that lightning damage reports in the Storm Events database often were lower than insured losses, in part because the Storm Events database missed many losses of $5,000 or less [Holle reference in \citet{Curran2000}].

Years after Hurricane Katrina, the database still did not have a precise estimate for associated fatalities, and was not confident it would in the future \citep{Ashley2008flood}.

Specific elements of event data can be particularly problematic. For example, a study of hail events found that around 30% of hail events within a test case had Storm Event listings for times or locations that were incorrect when comparing to radar data (in most of these cases, it appeared that the error was with the time of the event, and that most inaccuracies were an hour or shorter) \citep{Witt1998}. Similarly, elements like hail size can be unreliable, because spatial variations in hail size in an event can be much finer than the resolution of storm observation networks, like spotter networks or hail pads \citep{Witt1998}. A study of flood-related impacts found a substantial amount of missing data for the setting and activity associated with fatalities, as well as on the age and gender of the victim \cite{Ashley2008flood}. 

Collection of this storm data can be somewhat subjective. In particular, local storm events data is determined and supplied separately by the many different local NWS offices across the US \citep{Curran2000}. This means that observations in different locations are specified by different people. Since there is some level of individual judgement required for creating storm event entries, this could lead in some subjectivity in the data that is regionally clusetered by reporting NWS office, depending on the specific priorities of different offices \citep{Witt1998}. Regional trends in underreporting can also result from differences in observation networks, including severe weather spotter networks \citep{Witt1998}.

Some errors have been found in the database, including some incorrect property damage values in 1989 \citep{Curran2000}, ... . Another study found occasional typographical errors in event locations \citep{Witt1998}. Another study found discrepancies in data on shether type where fatalities occurred between coded data and information in descriptive paragraphs \cite{Ashley2007}.

Researchers have varied in the degree to which they cleaned or modified the databased before using it in research. A study of lightning impacts, for example, only cleaned a few incorrect damage values but otherwise used the database directly \citep{Curran2000}. A study of flood-related casualties excluded some observations (e.g., from Hurricane Katrina, because confident estimates were still lacking) prior to analysis \citep{Ashley2008flood}.

Despite these limitations, the Storm Events database is still critical for research, and is often the only available resource to use to study trends in events and impacts at a large spatial and temporal scale \citep{Ashley2008flood}. For example, the Storm Events database has a much larger coverage than more specialized storm events data like field project datasets (e.g., NCAR's hail project) \citep{Witt1998}.

## Literature review

Curran et al. (2000)

This paper by \citet{Curran2000} analyzes all 3239 deaths, 9818 injuries, and 19814 property damage reports in Storm Data publication by NCDC due to lightning from 1959 to 1994. It describes lightning casualties (deaths and injuries combined) and damage reports stratified by state and region of the United States, decade, population, time of year and day, and all other information in Storm Data.

   
Witt et al. (1998)

In \citet{Witt1998}, the authors introduce an enhanced hail detection algorithm (HDA) developed for the WSR-88D to replace the original hail algorithm. They developed a new parameter, called the severe hail index (SHI), as the primary predictor variable for severe-size hail. The SHI is a thermally weighted vertical integration of a storm cell’s reflectivity profile.  
The Storm Data (NCDC 1989, 1992) was used to provide severe hail reports, with ground-truth verification. These reports were then correlated to the algorithm output from running storm cell identification and tracking (SCIT) algorithm and HDA on the radar data. The whole process is intended to determine the utility of SHI as a severe hail predictor, WSR-88D level II data.


Ashley (2007)

This study by \citet{Ashley2007} compiles and analyzes a dataset of killer tornadoes spatially in order to examine region-specific vulnerabilities in the United States from 1880 to 2005. 
In this study the storm events database, along with a long-term study of U.S. tornadoes by Grazulis (1993, 1997, hereafter Grazulis dataset), provides U.S. tornado fatality information. Information from Storm Event database and the Storm Data reports from 1959 to 2005 supplement the existing record of killer tornado events documented by Grazulis.



Ashley et al. (2008 flood) 

In \citet{Ashley2008flood}, the authors compiled a nationwide database of flood fatalities for the contiguous United States from 1959 to 2005. Assembled data include the location of fatalities, age and gender of victims, activity and/or setting of fatalities, and the type of flood events responsible for each fatality report.
Fatality informtion in this compiled database was extracted from monthly reports from volumes 1–47 of the National Climatic Data Center’s (NCDC) Storm Data publication.
   
    
Schumacher et al. (2006) 

This study by \citet{Schumacher2006} covers 184 extreme rain events over the eastern two-thirds of the United States and examines their characteristics. The authors used information on flood events from the Storm Events Database to see whether the selected extreme rain events caused flash floods, damage, or injuries. In addition, since flash-flood-producing storms in the past have been associated with other types of severe weather (e.g., \citep{Smith2001extreme}; \citep{rogash2002some}), the proximity of severe wind, hail, and tornadoes to extreme rainfall could also be useful information.
For each extreme rain event, the storm events database was used to determine if flash flooding occurred at or near the location where the extreme rainfall totals were observed. If tornadoes were reported, the database was then checked to find their Fujita scale ratings. If flash flooding, severe wind, severe hail, tornadoes, or significant tornadoes (F2 or greater) were reported in conjunction with the extreme-rain-producing storm system at approximately the same time as the heavy rainfall was occurring, a “yes” was assigned for that phenomenon for that event.  


Akerlof et al. (2013)

In \citet{Akerlof2013}, the authors propose four research questions to study what signals of global warming some people believe they are detecting, why, and whether or not it is important. These four related studies were conducted using population survey and climatic data from a single county in Michigan.
The Storm Events Database was used to study the research question "are the self-reported local experiences of global warming evident in the local historical data records?" The authors extracted storm event frequenies information for Alger County from the database and compare them to local residents' perceptions of experienced storm event frequencies to see if the self reports were correct.    
    

Moskalski et al. (2013)

\citet{Moskalski2013} used the information from Storm Events Database to compare to the 11 years (2000-10) of continuous water level and turbidity data for the St. Jones River National Estuarine Research Reserve to determine which types of storms are most effective in flooding the marsh platform with high-turbidity water, a condition conducive for sedimentation.
The water-level and turbidity events were referenced to weather events registered in the Storm Events Database. Weather events were classified based on descriptions provided in the database and surface pressure data available through database.
    
  

Wade et al. (2014)

In \citet{Wade2014} the authors use the NOAA's Storm Events Database to obtain information on flood events. They wanted to investigate if there is a relationship between flooding and emergency room vists for gastrointestinal illness (ER-GI). 
They adopted a time-stratified bi-directional design for control selection, matching on day of the week with two weeks lead or lag time from the ER-GI visit. Fixed effect logistic regression models were used to estimate the risk of ER-GI visits following the flood. Storms with the event types "Coastal Floods", "Flash Floods", and related events occurring in the State of Massachusetts for the time period December 2002 through January 2008 were included in the analysis. Storms from 2002 and 2008 were included to allow for lagged and leading exposures of the 2003 ER visits and control periods.


Konisky et al. (2016)

This paper by \citet{Konisky2016} examines whether experience of extreme weather events such as excessive heat, droughts, flooding, and hurricanes increases an individual's level concern about climate change. To study this question, the authors bring together micro-level geospatial data on extreme weather events from NOAA's Storm Events Database with public opinion data from multiple years of the Cooperative Congressional Election Study.
    

Gallus et al. (2008)

In \citet{Gallus2008}, the authors use Radar data during the period 1 April – 31 August 2002 to classify all convective storms into nine predominant morphologies, and they analyze the severe weather reports associated with each morphology.
The storm events database was used to produce these severe weather reports and then these reports that occurred over the same time period were recorded, cataloged, and associated with the storm systems that identified from the radar data.
    
    
#"Tornado hazards in the United States"
Boruff et al. (2003)

In a paper by \citet{Boruff2003} examines the temporal variability and spatial distribution of tornado hazards in the United States. Tornado hazards are defined very specifically as any reported tornado that resulted in human injury, human fatality, or some amount of economic loss.
The Storm Events Database was employed to provide tornado data. These tornado data were incorporated into a geographical information system (GIS) to create a digital map (shapefile) using the touchdown locations (longitude/latitude), which were then put into an Albers equal area projection for mapping and analytical purposes.
One thing to notice is that the corrected and verified database was modified to include only tornado segments that resulted in any recorded impact measured as a death, an injury, or economic damage. Tornado segments that did not meet these criteria were deleted.
    
    
#"A REASSESSMENT OF U.S. LIGHTNING MORTALITY"
Ashley et al. (2009)

In \citet{Ashley2009}, the authors provide a reassessment of the risks and vulnerabilities that produce fatal lightning events and further illustrates the deficiencies of current post–hazard event data-gathering methods using a comprehensive lightning mortality dataset.
The authors collected data from Storm Event Database as well as monthly Storm Data publications from NCDC and and then assessed them for lightning mortality data to get this comprehensive lightning mortality dataset.


#"A test of porous pavement effectiveness on clay soils during natural storm events"
Dreelin et al. (2006) 

The purpose of this research by \citet{Dreelin2006} is to compile a database for the period 1980-2005 to assess the threat to life in the conterminous United States from nonconvective high-wind events.
The Storm Events Database provides casualty data from 1993 to 2005. From 1980 to 1992, data were transcribed from Storm Data publication from NCDC.


#"Vulnerability due to Nocturnal Tornadoes"
Ashley et al. (2008 tornadoes)

This research by \citet{ashley2008tornadoes} investigates the human vulnerability caused by tornadoes that occurred between sunset and sunrise from 1880 to 2007.
In order to get human vulnerability information, the authors utilized the National Climatic Data Center’s publication Storm Data (NCDC 1959–2007), NCDC’s Storm Event Database, and the historical archives of event and fatality data provided by NOAA Prediction Center to acquire historical tornado event and fatality data.
    

#"A Climatology of Fatal Convective Wind Events by Storm Type"
Schoen et al. (2011)

This research by \citet{Schoen2011} illustrates a spatial and temporal analysis of the storm morphological characteristics, or convective mode, of all fatal tornadic and nontornadic convective wind events from 1998 to 2007 using thunderstorm fatality and Weather Surveillance Radar-1988 Doppler (WSR-88D) data.
The Storm Events database was utilized to provide the fatality data. These data were used to determine the spatial and temporal information associated with each convective wind–related fatality in the United States from 1998 to 2007.
    
    
#"A Fingerprinting Technique for Major Weather Events"
Root et al. (2007)

In \citet{Root2007}, the author examine the utility of pattern recognition in assisting the prediction of severe and major weather in the Middle Atlantic region.
For objective identification of the patterns associated with major weather events, the authors generated a database from another research and used the Storm Events Database to verify this database. Besides, Storm Events Database also provides fire occurrences information in this research.
    

#"Climatology of Thunderstorms for North Dakota, 2002–06"
Mohee et al. (2010)

This paper by \citet{Mohee2010} aims to obtain the climatology of thunderstorms in the North Dakota by investigating radar and surface thunderstorm data in the state.
The Storm Events Database was used to provide information on damages due to thunderstorms and other natural calamities in North Dakota for 1993–2010.
 
\bibliography{RJreferences}
