language: r
warnings_are_errors: true
sudo: false
cache: packages

dist: trusty

before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev

r_github_packages:
  - geanders/hurricaneexposuredata
