language: r
warnings_are_errors: true
sudo: false
cache: packages

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

before_install: |
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11
  CXX=gcc-4.9

r_github_packages:
  - geanders/hurricaneexposuredata
