language: r
warnings_are_errors: true
sudo: false
cache: packages

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

r_github_packages:
  - geanders/hurricaneexposuredata
